### ISSUE TITLE
Works perfect in debian buster 64 bit but not in 32 bit

### ISSUE THREAD

**Issue by dkdjam** [osxmidi/LinVst#128]
Hey, I really appreciate using LinVst as I can finally get Addictive Drums 2 to be inserted as a plugin in ardour. My issue is this:

-  I have 2 PCs, one is 64 bit, i7 CPU, the other is an old workstation I built myself 12 years ago, which still works perfectly fine (it has an old PCI HDSP card + Multiface II IO box, which I am not going to update to PCIe due to economic reason :D ).

On both machines, I run debian buster, wine staging 4.20, ardour 5.12, etc. It's exactly the same environment save for the architecture. Here is now the problem:

on the 32 bit machine, LinVst seems to be installed correctly, i.e. TestVst brings up the Addictive Drums window for a few seconds. I have the AD dll run in fsthost perfectly fine as well. But when I ask the ardour-vst-scanner to test it, it reports a LinVst error (instantiation failure), this is also the case with other VSTs I have around.

I would like the same ability to run my drum VST as a plugin in ardour on the 32 bit PC. I use the 64 bit machine in our rehearsal room (plugged to a couple of MOTU 8pre modules via firewire) but the data disk is shared and I always bring it back home to my 32 bit PC for extra work on the recorded material.  

SO, to summrize:
Environment identical (debian buster), same software versions
64 bit -> perfect
32 bit -> ardour fails to instantiate the VST

Would you have any tip on how to troubleshoot ? I am not new at this kind of things but I don't have much time these days. Any tip would be appreciated. Thanks for the good work!

**Comment by osxmidi** [comment]
I had something wrong for the 32 bit builds.

I've fixed it now.

If it doesn't work let me know.

**Comment by dkdjam** [comment]
Cool, I will give it a try tonight, will let you know for sure.

**Comment by dkdjam** [comment]
I gave it a quick try after thoroughly cleaning up everything but I still have the same issue, ardour-vst-scanner reports the same messages (instantiation issue) even though TestVst has no issue opening up the VST GUI.

**Comment by dkdjam** [comment]
Hey, I came back to it 10mn ago and recompiled from scratch using the standalone makefile for 32 bit. It now works, i.e. I can instantiate the plugin from a MIDI track in ardour. It seems to run nicely. Now, can you explain the diff between embedded and standalone in the context of linvst ?

**Comment by osxmidi** [comment]
> Hey, I came back to it 10mn ago and recompiled from scratch without using the deb stuff. It now works, i.e. I can instantiate the plugin from a MIDI track in ardour. It seems to run nicely. Now, can you explain the diff between embedded and standalone in the context of linvst ?

When the daw opens a plugin it also creates a window that the plugin can use, and then the plugin embeds it's window into the daw's plugin window.

The standalone window version has it's own window and the daw's plugin window is ignored.

The standalone window version is really an optional extra and I mostly keep it around as a way of testing possible display problems.

**Comment by dkdjam** [comment]
I see. I will try again to use the embedded lib. I see no obvious reason why it shouldn't work. But I am glad it works at all :) The flow is so much better in that way!
