### ISSUE TITLE
Toneboosters Isone - Knobs not working/moving slow

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#16]
When using Toneboosters Isone Plugin (available here: https://www.toneboosters.com/downloads/TB_Portable_v1.0.4_win.zip) the knobs are not working or moving so slow, you can't actually work with it in Ardour. The plugin works rather fine with airwave in Bitwig (32bit) and Carla (32bit) in Ardour. I tried both 32 and 64 bit in LinVST and Ardour 5.10, both not working.

P.S.: Thanks for your great work! I love this. It supports far more winVSTs in Ardour than airwave, except - see above ;)

**Comment by osxmidi** [comment]
Thanks for the feedback.

All fixed in LinVst 1.5.1

**Comment by lentferj** [comment]
That was quick :). Buttons work now, thanks a lot. One little hiccup still exists: If you click the "Preset" or "Channel Mode" Menus, the drop down will open somewhere else on the screen (in my case on the primary monitor, while the plugin GUI is on the secondary monitor). It seems they are appearing in a fixed place relative to 0,0 (left top).
